package data.problems;

import data.AbstractProblem;

public class Problem002 extends AbstractProblem
{
    public Problem002()
    {
        setNumber( 2 );
        setDescription( "<html>Each new term in the Fibonacci sequence is generated by<br>"
                + "adding the previous two terms. By starting with 1 and 2, the <br>"
                + "first 10 terms will be:<br>"
                + "<b>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</b><br><br>"
                + "By considering the terms in the Fibonacci sequence whose values<br>"
                + "do not exceed four million, find the sum of the even-valued terms.</html>" );
    }

    @Override
    public String getSolution()
    {
        long sum = 0;

        int prevTerm = 1;
        int nextTerm = 2;
        int temp;
        while( nextTerm < 4000000 )
        {
            if( nextTerm % 2 == 0 )
                sum += nextTerm;
            temp = prevTerm + nextTerm;
            prevTerm = nextTerm;
            nextTerm = temp;
        }

        return "Sum: " + sum;
    }

}
